using System.Text;

namespace UltimateVideoBrowser.LicenseServer.Services;

public static class LandingPageBuilder
{
    public static string BuildLandingPage()
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"de\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"utf-8\" />");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
        sb.AppendLine("  <title>UltimateVideoBrowser Pro</title>");
        sb.AppendLine("  <link rel=\"preconnect\" href=\"https://images.unsplash.com\" />");
        sb.AppendLine("  <style>");
        sb.AppendLine("    :root{--bg:#0b1020;--panel:#151b2c;--accent:#6d7bff;--accent-2:#8be1ff;--text:#f8fafc;--muted:#cbd5f5;}");
        sb.AppendLine("    *{box-sizing:border-box}");
        sb.AppendLine("    body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,\"Helvetica Neue\",Arial;background:var(--bg);color:var(--text);line-height:1.5}");
        sb.AppendLine("    header{position:relative;overflow:hidden;padding:48px 0 80px;background:radial-gradient(circle at 15% 15%,rgba(109,123,255,.35),transparent 50%),radial-gradient(circle at 80% 10%,rgba(139,225,255,.25),transparent 40%),linear-gradient(135deg,#0d1228 0%,#111a33 100%)}");
        sb.AppendLine("    .container{max-width:1200px;margin:0 auto;padding:0 24px}");
        sb.AppendLine("    .topbar{display:flex;align-items:center;justify-content:space-between;gap:16px}");
        sb.AppendLine("    .brand{display:flex;align-items:center;gap:14px;font-weight:700;font-size:20px}");
        sb.AppendLine("    .brand img{width:42px;height:42px}");
        sb.AppendLine("    .lang-select{position:fixed;top:18px;right:20px;background:rgba(8,12,25,.7);border:1px solid rgba(255,255,255,.2);color:var(--text);padding:8px 12px;border-radius:12px;backdrop-filter:blur(8px);z-index:1000}");
        sb.AppendLine("    .hero{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:40px;align-items:center;margin-top:48px}");
        sb.AppendLine("    .hero h1{font-size:42px;margin:0 0 12px}");
        sb.AppendLine("    .hero p{color:var(--muted);font-size:18px;margin:0 0 24px}");
        sb.AppendLine("    .cta{display:flex;flex-wrap:wrap;gap:16px}");
        sb.AppendLine("    .btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 20px;border-radius:12px;border:1px solid transparent;font-weight:600;text-decoration:none;transition:.2s}");
        sb.AppendLine("    .btn.primary{background:var(--accent);color:white;box-shadow:0 10px 25px rgba(109,123,255,.35)}");
        sb.AppendLine("    .btn.secondary{border-color:rgba(255,255,255,.3);color:var(--text);background:rgba(255,255,255,.04)}");
        sb.AppendLine("    .stats{display:flex;flex-wrap:wrap;gap:20px;margin-top:24px}");
        sb.AppendLine("    .stat{background:rgba(255,255,255,.06);padding:14px 18px;border-radius:14px;border:1px solid rgba(255,255,255,.1);min-width:160px}");
        sb.AppendLine("    .stat strong{display:block;font-size:22px}");
        sb.AppendLine("    .hero-media{position:relative}");
        sb.AppendLine("    .hero-card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:20px;box-shadow:0 25px 60px rgba(0,0,0,.35)}");
        sb.AppendLine("    .hero-card img{width:100%;border-radius:16px}");
        sb.AppendLine("    .section{padding:72px 0}");
        sb.AppendLine("    .section-title{font-size:32px;margin:0 0 16px}");
        sb.AppendLine("    .section-sub{color:var(--muted);max-width:720px;margin:0 0 32px}");
        sb.AppendLine("    .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px}");
        sb.AppendLine("    .card{background:var(--panel);border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:20px;display:flex;flex-direction:column;gap:12px;min-height:180px}");
        sb.AppendLine("    .card img{width:40px;height:40px}");
        sb.AppendLine("    .card h3{margin:0}");
        sb.AppendLine("    .card p{margin:0;color:var(--muted)}");
        sb.AppendLine("    .showcase{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px}");
        sb.AppendLine("    .showcase img{width:100%;border-radius:18px;border:1px solid rgba(255,255,255,.12)}");
        sb.AppendLine("    .pill{display:inline-flex;align-items:center;gap:8px;background:rgba(109,123,255,.15);border:1px solid rgba(109,123,255,.4);padding:6px 14px;border-radius:999px;font-weight:600;font-size:13px}");
        sb.AppendLine("    .pricing{background:linear-gradient(135deg,rgba(109,123,255,.15),rgba(139,225,255,.12));border:1px solid rgba(255,255,255,.14);border-radius:24px;padding:32px;display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px;align-items:center}");
        sb.AppendLine("    .pricing .price{font-size:40px;font-weight:800}");
        sb.AppendLine("    footer{padding:40px 0;color:var(--muted);border-top:1px solid rgba(255,255,255,.08)}");
        sb.AppendLine("    footer a{color:var(--text);text-decoration:none}");
        sb.AppendLine("    .legal-links{display:flex;gap:16px;flex-wrap:wrap}");
        sb.AppendLine("    .floating-glow{position:absolute;right:-80px;top:60px;width:240px;height:240px;background:radial-gradient(circle,rgba(109,123,255,.6),transparent 70%);filter:blur(4px);opacity:.7}");
        sb.AppendLine("    @media (max-width:720px){.hero h1{font-size:34px}.lang-select{top:12px;right:12px}}");
        sb.AppendLine("  </style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<select class=\"lang-select\" id=\"langSelect\" aria-label=\"Language\"></select>");
        sb.AppendLine("<header>");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <div class=\"topbar\">");
        sb.AppendLine("      <div class=\"brand\"><img src=\"/assets/appicon.svg\" alt=\"UltimateVideoBrowser\" /><span>UltimateVideoBrowser Pro</span></div>");
        sb.AppendLine("      <a class=\"btn secondary\" href=\"#pricing\" data-i18n=\"nav_pricing\">Preis & Lizenz</a>");
        sb.AppendLine("    </div>");
        sb.AppendLine("    <div class=\"hero\">");
        sb.AppendLine("      <div>");
        sb.AppendLine("        <span class=\"pill\" data-i18n=\"pill\">Premium Medien-Kontrolle</span>");
        sb.AppendLine("        <h1 data-i18n=\"hero_title\">Die professionelle Medienzentrale für Menschen, die keine Kompromisse akzeptieren.</h1>");
        sb.AppendLine("        <p data-i18n=\"hero_subtitle\">Durchsuche, indexiere und erlebe deine Videos, Fotos und Dokumente in Sekunden – mit einer Oberfläche, die sich wie Magie anfühlt.</p>");
        sb.AppendLine("        <div class=\"cta\">");
        sb.AppendLine("          <form action=\"/api/checkout\" method=\"post\" style=\"display:inline\">");
        sb.AppendLine("            <button class=\"btn primary\" type=\"submit\" data-i18n=\"cta_primary\">Jetzt Pro freischalten</button>");
        sb.AppendLine("          </form>");
        sb.AppendLine("          <a class=\"btn secondary\" href=\"#features\" data-i18n=\"cta_secondary\">Funktionen entdecken</a>");
        sb.AppendLine("        </div>");
        sb.AppendLine("        <div class=\"stats\">");
        sb.AppendLine("          <div class=\"stat\"><strong data-i18n=\"stat_one_value\">3×</strong><span data-i18n=\"stat_one_label\">schnelleres Finden</span></div>");
        sb.AppendLine("          <div class=\"stat\"><strong data-i18n=\"stat_two_value\">1 Klick</strong><span data-i18n=\"stat_two_label\">bis zur perfekten Ansicht</span></div>");
        sb.AppendLine("          <div class=\"stat\"><strong data-i18n=\"stat_three_value\">100%</strong><span data-i18n=\"stat_three_label\">Fokus auf deine Daten</span></div>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </div>");
        sb.AppendLine("      <div class=\"hero-media\">");
        sb.AppendLine("        <div class=\"floating-glow\"></div>");
        sb.AppendLine("        <div class=\"hero-card\">");
        sb.AppendLine("          <img src=\"/assets/hero_video.svg\" alt=\"App Vorschau\" />");
        sb.AppendLine("          <p data-i18n=\"hero_image_caption\" style=\"margin-top:12px;color:var(--muted);\">App-Visualisierung mit originalen Assets</p>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</header>");
        sb.AppendLine("<section class=\"section\" id=\"features\">");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <h2 class=\"section-title\" data-i18n=\"features_title\">Ein Erlebnis, das deine Medien auf ein neues Level hebt</h2>");
        sb.AppendLine("    <p class=\"section-sub\" data-i18n=\"features_sub\">UltimateVideoBrowser Pro kombiniert Geschwindigkeit, Intelligenz und Design zu einer Medienplattform, die dich nie warten lässt.</p>");
        sb.AppendLine("    <div class=\"grid\">");
        sb.AppendLine("      <div class=\"card\"><img src=\"/assets/icon_sources.svg\" alt=\"Sources\" /><h3 data-i18n=\"feature_one_title\">Smarter Quellen-Manager</h3><p data-i18n=\"feature_one_desc\">Verbinde Ordner, Laufwerke und Cloud-Backups – automatisch organisiert, immer bereit.</p></div>");
        sb.AppendLine("      <div class=\"card\"><img src=\"/assets/icon_play.svg\" alt=\"Playback\" /><h3 data-i18n=\"feature_two_title\">Sofortige Vorschau</h3><p data-i18n=\"feature_two_desc\">Sieh wichtige Momente direkt – keine Wartezeiten, keine Unterbrechungen.</p></div>");
        sb.AppendLine("      <div class=\"card\"><img src=\"/assets/icon_people.svg\" alt=\"People\" /><h3 data-i18n=\"feature_three_title\">Intelligente Erkennung</h3><p data-i18n=\"feature_three_desc\">Finde Inhalte über Gesichter, Orte oder Tags. Deine Bibliothek reagiert, bevor du fragst.</p></div>");
        sb.AppendLine("      <div class=\"card\"><img src=\"/assets/chip_spark.svg\" alt=\"AI\" /><h3 data-i18n=\"feature_four_title\">Turbo-Indexierung</h3><p data-i18n=\"feature_four_desc\">Ein neues Level an Performance sorgt dafür, dass selbst riesige Sammlungen sofort durchsucht werden.</p></div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</section>");
        sb.AppendLine("<section class=\"section\" style=\"background:#0f152b\">");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <h2 class=\"section-title\" data-i18n=\"gallery_title\">Design, das Vertrauen schafft</h2>");
        sb.AppendLine("    <p class=\"section-sub\" data-i18n=\"gallery_sub\">Professionelle Grafiken und echte App-Assets geben dir den Premium-Eindruck, den deine Medien verdienen.</p>");
        sb.AppendLine("    <div class=\"showcase\">");
        sb.AppendLine("      <div>");
        sb.AppendLine("        <img src=\"https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80\" alt=\"Cinematic visuals\" />");
        sb.AppendLine("        <p data-i18n=\"gallery_caption_one\" style=\"color:var(--muted);margin-top:12px\">Kino-Look für deine Bibliothek – inspiriert von freien Unsplash-Grafiken.</p>");
        sb.AppendLine("      </div>");
        sb.AppendLine("      <div>");
        sb.AppendLine("        <img src=\"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80\" alt=\"Technology\" />");
        sb.AppendLine("        <p data-i18n=\"gallery_caption_two\" style=\"color:var(--muted);margin-top:12px\">Technologie-Ästhetik, die Professionalität ausstrahlt.</p>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</section>");
        sb.AppendLine("<section class=\"section\" id=\"pricing\">");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <div class=\"pricing\">");
        sb.AppendLine("      <div>");
        sb.AppendLine("        <h2 class=\"section-title\" data-i18n=\"pricing_title\">Einmal bezahlen. Für immer genießen.</h2>");
        sb.AppendLine("        <p class=\"section-sub\" data-i18n=\"pricing_sub\">Keine Abos, keine versteckten Gebühren. Einmal freischalten und alle Pro-Features dauerhaft nutzen.</p>");
        sb.AppendLine("        <div class=\"legal-links\">");
        sb.AppendLine("          <a href=\"/agb\" data-i18n=\"link_terms\">AGB</a>");
        sb.AppendLine("          <a href=\"/datenschutz\" data-i18n=\"link_privacy\">Datenschutz</a>");
        sb.AppendLine("          <a href=\"/impressum\" data-i18n=\"link_imprint\">Impressum</a>");
        sb.AppendLine("          <a href=\"/widerruf\" data-i18n=\"link_withdrawal\">Widerruf</a>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </div>");
        sb.AppendLine("      <div>");
        sb.AppendLine("        <div class=\"price\" data-i18n=\"pricing_value\">€39</div>");
        sb.AppendLine("        <p data-i18n=\"pricing_note\">inkl. Updates für die aktuelle Hauptversion</p>");
        sb.AppendLine("        <form action=\"/api/checkout\" method=\"post\" style=\"display:inline\">");
        sb.AppendLine("          <button class=\"btn primary\" type=\"submit\" data-i18n=\"pricing_cta\">Pro jetzt sichern</button>");
        sb.AppendLine("        </form>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</section>");
        sb.AppendLine("<section class=\"section\" style=\"padding-top:0\">");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <h2 class=\"section-title\" data-i18n=\"trust_title\">Entwickelt für Profis, geliebt von Enthusiasten</h2>");
        sb.AppendLine("    <p class=\"section-sub\" data-i18n=\"trust_sub\">Vom Hobbyfilmer bis zum Studio-Team: UltimateVideoBrowser Pro schafft Ordnung, Geschwindigkeit und Wow-Momente.</p>");
        sb.AppendLine("    <div class=\"grid\">");
        sb.AppendLine("      <div class=\"card\"><h3 data-i18n=\"trust_one_title\">Plattformübergreifend</h3><p data-i18n=\"trust_one_desc\">Nutze deine Lizenz flexibel auf Windows und Android – mit derselben Premium-Erfahrung.</p></div>");
        sb.AppendLine("      <div class=\"card\"><h3 data-i18n=\"trust_two_title\">Offline bereit</h3><p data-i18n=\"trust_two_desc\">Selbst ohne Internet bleibt deine Medienbibliothek verfügbar – dank sicherer Offline-Aktivierung.</p></div>");
        sb.AppendLine("      <div class=\"card\"><h3 data-i18n=\"trust_three_title\">Datenschutz inklusive</h3><p data-i18n=\"trust_three_desc\">Deine Inhalte bleiben deine Inhalte. Keine Cloud-Pflicht, keine Datenverwertung.</p></div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</section>");
        sb.AppendLine("<footer>");
        sb.AppendLine("  <div class=\"container\">");
        sb.AppendLine("    <div class=\"topbar\">");
        sb.AppendLine("      <div class=\"brand\"><img src=\"/assets/app_logo.svg\" alt=\"UltimateVideoBrowser Logo\" /><span data-i18n=\"footer_brand\">Medien, die sich wie Zukunft anfühlen.</span></div>");
        sb.AppendLine("      <div class=\"legal-links\">");
        sb.AppendLine("        <a href=\"/agb\" data-i18n=\"link_terms\">AGB</a>");
        sb.AppendLine("        <a href=\"/datenschutz\" data-i18n=\"link_privacy\">Datenschutz</a>");
        sb.AppendLine("        <a href=\"/impressum\" data-i18n=\"link_imprint\">Impressum</a>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("    <p style=\"margin-top:20px\" data-i18n=\"footer_note\">UltimateVideoBrowser Pro – der neue Standard für anspruchsvolle Medienverwaltung.</p>");
        sb.AppendLine("  </div>");
        sb.AppendLine("</footer>");
        sb.AppendLine("<script>");
        sb.AppendLine("const translations = {");
        sb.AppendLine("  de: {");
        sb.AppendLine("    nav_pricing: 'Preis & Lizenz',");
        sb.AppendLine("    pill: 'Premium Medien-Kontrolle',");
        sb.AppendLine("    hero_title: 'Die professionelle Medienzentrale für Menschen, die keine Kompromisse akzeptieren.',");
        sb.AppendLine("    hero_subtitle: 'Durchsuche, indexiere und erlebe deine Videos, Fotos und Dokumente in Sekunden – mit einer Oberfläche, die sich wie Magie anfühlt.',");
        sb.AppendLine("    cta_primary: 'Jetzt Pro freischalten',");
        sb.AppendLine("    cta_secondary: 'Funktionen entdecken',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'schnelleres Finden',");
        sb.AppendLine("    stat_two_value: '1 Klick',");
        sb.AppendLine("    stat_two_label: 'bis zur perfekten Ansicht',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'Fokus auf deine Daten',");
        sb.AppendLine("    hero_image_caption: 'App-Visualisierung mit originalen Assets',");
        sb.AppendLine("    features_title: 'Ein Erlebnis, das deine Medien auf ein neues Level hebt',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro kombiniert Geschwindigkeit, Intelligenz und Design zu einer Medienplattform, die dich nie warten lässt.',");
        sb.AppendLine("    feature_one_title: 'Smarter Quellen-Manager',");
        sb.AppendLine("    feature_one_desc: 'Verbinde Ordner, Laufwerke und Cloud-Backups – automatisch organisiert, immer bereit.',");
        sb.AppendLine("    feature_two_title: 'Sofortige Vorschau',");
        sb.AppendLine("    feature_two_desc: 'Sieh wichtige Momente direkt – keine Wartezeiten, keine Unterbrechungen.',");
        sb.AppendLine("    feature_three_title: 'Intelligente Erkennung',");
        sb.AppendLine("    feature_three_desc: 'Finde Inhalte über Gesichter, Orte oder Tags. Deine Bibliothek reagiert, bevor du fragst.',");
        sb.AppendLine("    feature_four_title: 'Turbo-Indexierung',");
        sb.AppendLine("    feature_four_desc: 'Ein neues Level an Performance sorgt dafür, dass selbst riesige Sammlungen sofort durchsucht werden.',");
        sb.AppendLine("    gallery_title: 'Design, das Vertrauen schafft',");
        sb.AppendLine("    gallery_sub: 'Professionelle Grafiken und echte App-Assets geben dir den Premium-Eindruck, den deine Medien verdienen.',");
        sb.AppendLine("    gallery_caption_one: 'Kino-Look für deine Bibliothek – inspiriert von freien Unsplash-Grafiken.',");
        sb.AppendLine("    gallery_caption_two: 'Technologie-Ästhetik, die Professionalität ausstrahlt.',");
        sb.AppendLine("    pricing_title: 'Einmal bezahlen. Für immer genießen.',");
        sb.AppendLine("    pricing_sub: 'Keine Abos, keine versteckten Gebühren. Einmal freischalten und alle Pro-Features dauerhaft nutzen.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'inkl. Updates für die aktuelle Hauptversion',");
        sb.AppendLine("    pricing_cta: 'Pro jetzt sichern',");
        sb.AppendLine("    trust_title: 'Entwickelt für Profis, geliebt von Enthusiasten',");
        sb.AppendLine("    trust_sub: 'Vom Hobbyfilmer bis zum Studio-Team: UltimateVideoBrowser Pro schafft Ordnung, Geschwindigkeit und Wow-Momente.',");
        sb.AppendLine("    trust_one_title: 'Plattformübergreifend',");
        sb.AppendLine("    trust_one_desc: 'Nutze deine Lizenz flexibel auf Windows und Android – mit derselben Premium-Erfahrung.',");
        sb.AppendLine("    trust_two_title: 'Offline bereit',");
        sb.AppendLine("    trust_two_desc: 'Selbst ohne Internet bleibt deine Medienbibliothek verfügbar – dank sicherer Offline-Aktivierung.',");
        sb.AppendLine("    trust_three_title: 'Datenschutz inklusive',");
        sb.AppendLine("    trust_three_desc: 'Deine Inhalte bleiben deine Inhalte. Keine Cloud-Pflicht, keine Datenverwertung.',");
        sb.AppendLine("    link_terms: 'AGB',");
        sb.AppendLine("    link_privacy: 'Datenschutz',");
        sb.AppendLine("    link_imprint: 'Impressum',");
        sb.AppendLine("    link_withdrawal: 'Widerruf',");
        sb.AppendLine("    footer_brand: 'Medien, die sich wie Zukunft anfühlen.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro – der neue Standard für anspruchsvolle Medienverwaltung.'");
        sb.AppendLine("  },");
        sb.AppendLine("  en: {");
        sb.AppendLine("    nav_pricing: 'Pricing & License',");
        sb.AppendLine("    pill: 'Premium media control',");
        sb.AppendLine("    hero_title: 'The professional media command center for people who refuse to compromise.',");
        sb.AppendLine("    hero_subtitle: 'Search, index, and experience your videos, photos, and documents in seconds with an interface that feels like magic.',");
        sb.AppendLine("    cta_primary: 'Unlock Pro now',");
        sb.AppendLine("    cta_secondary: 'Explore features',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'faster discovery',");
        sb.AppendLine("    stat_two_value: '1 click',");
        sb.AppendLine("    stat_two_label: 'to the perfect view',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'focus on your data',");
        sb.AppendLine("    hero_image_caption: 'App visualization with original assets',");
        sb.AppendLine("    features_title: 'An experience that elevates every media moment',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro blends speed, intelligence, and design into a platform that never keeps you waiting.',");
        sb.AppendLine("    feature_one_title: 'Smart source manager',");
        sb.AppendLine("    feature_one_desc: 'Connect folders, drives, and backups—organized automatically and always ready.',");
        sb.AppendLine("    feature_two_title: 'Instant preview',");
        sb.AppendLine("    feature_two_desc: 'See key moments right away—no waiting, no interruptions.',");
        sb.AppendLine("    feature_three_title: 'Intelligent recognition',");
        sb.AppendLine("    feature_three_desc: 'Find content by faces, places, or tags. Your library responds before you ask.',");
        sb.AppendLine("    feature_four_title: 'Turbo indexing',");
        sb.AppendLine("    feature_four_desc: 'A new performance level ensures even massive libraries are searchable instantly.',");
        sb.AppendLine("    gallery_title: 'Design that builds trust',");
        sb.AppendLine("    gallery_sub: 'Professional graphics and real app assets deliver the premium impression your media deserves.',");
        sb.AppendLine("    gallery_caption_one: 'Cinematic styling for your library—powered by free Unsplash visuals.',");
        sb.AppendLine("    gallery_caption_two: 'Technology aesthetics that radiate professionalism.',");
        sb.AppendLine("    pricing_title: 'Pay once. Enjoy forever.',");
        sb.AppendLine("    pricing_sub: 'No subscriptions, no hidden fees. Unlock once and keep every Pro feature.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'includes updates for the current major version',");
        sb.AppendLine("    pricing_cta: 'Secure Pro now',");
        sb.AppendLine("    trust_title: 'Built for professionals, loved by enthusiasts',");
        sb.AppendLine("    trust_sub: 'From hobby filmmakers to studio teams: UltimateVideoBrowser Pro delivers order, speed, and wow moments.',");
        sb.AppendLine("    trust_one_title: 'Cross-platform',");
        sb.AppendLine("    trust_one_desc: 'Use your license flexibly on Windows and Android with the same premium experience.',");
        sb.AppendLine("    trust_two_title: 'Offline ready',");
        sb.AppendLine("    trust_two_desc: 'Even without internet, your media library stays available through secure offline activation.',");
        sb.AppendLine("    trust_three_title: 'Privacy included',");
        sb.AppendLine("    trust_three_desc: 'Your content stays yours. No mandatory cloud, no data harvesting.',");
        sb.AppendLine("    link_terms: 'Terms',");
        sb.AppendLine("    link_privacy: 'Privacy',");
        sb.AppendLine("    link_imprint: 'Imprint',");
        sb.AppendLine("    link_withdrawal: 'Withdrawal',");
        sb.AppendLine("    footer_brand: 'Media that feels like the future.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — the new standard for discerning media management.'");
        sb.AppendLine("  },");
        sb.AppendLine("  fr: {");
        sb.AppendLine("    nav_pricing: 'Tarifs & licence',");
        sb.AppendLine("    pill: 'Contrôle média premium',");
        sb.AppendLine("    hero_title: 'Le centre de commande média professionnel pour ceux qui refusent les compromis.',");
        sb.AppendLine("    hero_subtitle: 'Recherchez, indexez et vivez vos vidéos, photos et documents en quelques secondes avec une interface magique.',");
        sb.AppendLine("    cta_primary: 'Débloquer Pro',");
        sb.AppendLine("    cta_secondary: 'Découvrir les fonctionnalités',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'recherche plus rapide',");
        sb.AppendLine("    stat_two_value: '1 clic',");
        sb.AppendLine("    stat_two_label: 'pour la vue idéale',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'axé sur vos données',");
        sb.AppendLine("    hero_image_caption: 'Visualisation de l’app avec les assets originaux',");
        sb.AppendLine("    features_title: 'Une expérience qui sublime chaque média',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro associe vitesse, intelligence et design pour ne jamais vous faire attendre.',");
        sb.AppendLine("    feature_one_title: 'Gestion intelligente des sources',");
        sb.AppendLine("    feature_one_desc: 'Connectez dossiers, disques et sauvegardes — organisation automatique, toujours prête.',");
        sb.AppendLine("    feature_two_title: 'Aperçu instantané',");
        sb.AppendLine("    feature_two_desc: 'Voyez les moments clés immédiatement — sans attente ni interruption.',");
        sb.AppendLine("    feature_three_title: 'Reconnaissance intelligente',");
        sb.AppendLine("    feature_three_desc: 'Retrouvez du contenu par visages, lieux ou tags. Votre bibliothèque anticipe vos besoins.',");
        sb.AppendLine("    feature_four_title: 'Indexation turbo',");
        sb.AppendLine("    feature_four_desc: 'Un niveau de performance inédit rend même les grandes bibliothèques instantanément consultables.',");
        sb.AppendLine("    gallery_title: 'Un design qui inspire confiance',");
        sb.AppendLine("    gallery_sub: 'Des graphismes professionnels et les assets réels de l’app offrent une impression premium.',");
        sb.AppendLine("    gallery_caption_one: 'Un style cinématographique pour votre bibliothèque — inspiré par des visuels Unsplash libres.',");
        sb.AppendLine("    gallery_caption_two: 'Une esthétique technologique qui rayonne de professionnalisme.',");
        sb.AppendLine("    pricing_title: 'Payez une fois. Profitez pour toujours.',");
        sb.AppendLine("    pricing_sub: 'Aucun abonnement, aucun frais caché. Débloquez une fois et gardez toutes les fonctionnalités Pro.',");
        sb.AppendLine("    pricing_value: '39 €',");
        sb.AppendLine("    pricing_note: 'inclut les mises à jour de la version majeure actuelle',");
        sb.AppendLine("    pricing_cta: 'Obtenir Pro',");
        sb.AppendLine("    trust_title: 'Conçu pour les pros, adoré par les passionnés',");
        sb.AppendLine("    trust_sub: 'Des cinéastes amateurs aux studios: UltimateVideoBrowser Pro apporte ordre, vitesse et effet wow.',");
        sb.AppendLine("    trust_one_title: 'Multi-plateforme',");
        sb.AppendLine("    trust_one_desc: 'Utilisez votre licence sur Windows et Android avec la même expérience premium.',");
        sb.AppendLine("    trust_two_title: 'Prêt hors ligne',");
        sb.AppendLine("    trust_two_desc: 'Même sans internet, votre médiathèque reste disponible grâce à une activation hors ligne sécurisée.',");
        sb.AppendLine("    trust_three_title: 'Confidentialité incluse',");
        sb.AppendLine("    trust_three_desc: 'Vos contenus restent les vôtres. Pas de cloud obligatoire, pas de revente des données.',");
        sb.AppendLine("    link_terms: 'Conditions',");
        sb.AppendLine("    link_privacy: 'Confidentialité',");
        sb.AppendLine("    link_imprint: 'Mentions légales',");
        sb.AppendLine("    link_withdrawal: 'Rétractation',");
        sb.AppendLine("    footer_brand: 'Des médias qui donnent un goût de futur.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — la nouvelle référence pour une gestion média exigeante.'");
        sb.AppendLine("  },");
        sb.AppendLine("  es: {");
        sb.AppendLine("    nav_pricing: 'Precio y licencia',");
        sb.AppendLine("    pill: 'Control multimedia premium',");
        sb.AppendLine("    hero_title: 'El centro profesional de medios para quienes no aceptan compromisos.',");
        sb.AppendLine("    hero_subtitle: 'Busca, indexa y disfruta tus videos, fotos y documentos en segundos con una interfaz que parece magia.',");
        sb.AppendLine("    cta_primary: 'Desbloquear Pro',");
        sb.AppendLine("    cta_secondary: 'Descubrir funciones',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'búsqueda más rápida',");
        sb.AppendLine("    stat_two_value: '1 clic',");
        sb.AppendLine("    stat_two_label: 'para la vista perfecta',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'enfocado en tus datos',");
        sb.AppendLine("    hero_image_caption: 'Visualización de la app con recursos originales',");
        sb.AppendLine("    features_title: 'Una experiencia que eleva cada medio',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro combina velocidad, inteligencia y diseño para que nunca esperes.',");
        sb.AppendLine("    feature_one_title: 'Gestor de fuentes inteligente',");
        sb.AppendLine("    feature_one_desc: 'Conecta carpetas, discos y respaldos: organización automática, siempre lista.',");
        sb.AppendLine("    feature_two_title: 'Vista previa instantánea',");
        sb.AppendLine("    feature_two_desc: 'Mira los momentos clave al instante: sin esperas ni interrupciones.',");
        sb.AppendLine("    feature_three_title: 'Reconocimiento inteligente',");
        sb.AppendLine("    feature_three_desc: 'Encuentra contenido por rostros, lugares o etiquetas. Tu biblioteca se anticipa.',");
        sb.AppendLine("    feature_four_title: 'Indexación turbo',");
        sb.AppendLine("    feature_four_desc: 'Un nuevo nivel de rendimiento hace que incluso bibliotecas enormes sean buscables al instante.',");
        sb.AppendLine("    gallery_title: 'Diseño que genera confianza',");
        sb.AppendLine("    gallery_sub: 'Gráficos profesionales y assets reales de la app dan una impresión premium.',");
        sb.AppendLine("    gallery_caption_one: 'Estética cinematográfica para tu biblioteca — inspirada en visuales libres de Unsplash.',");
        sb.AppendLine("    gallery_caption_two: 'Estética tecnológica que transmite profesionalidad.',");
        sb.AppendLine("    pricing_title: 'Paga una vez. Disfruta para siempre.',");
        sb.AppendLine("    pricing_sub: 'Sin suscripciones ni cargos ocultos. Desbloquea una vez y conserva todo lo Pro.',");
        sb.AppendLine("    pricing_value: '39 €',");
        sb.AppendLine("    pricing_note: 'incluye actualizaciones de la versión mayor actual',");
        sb.AppendLine("    pricing_cta: 'Asegurar Pro',");
        sb.AppendLine("    trust_title: 'Creado para profesionales, amado por entusiastas',");
        sb.AppendLine("    trust_sub: 'Desde creadores hasta estudios: UltimateVideoBrowser Pro aporta orden, velocidad y efecto wow.',");
        sb.AppendLine("    trust_one_title: 'Multiplataforma',");
        sb.AppendLine("    trust_one_desc: 'Usa tu licencia en Windows y Android con la misma experiencia premium.',");
        sb.AppendLine("    trust_two_title: 'Listo sin conexión',");
        sb.AppendLine("    trust_two_desc: 'Incluso sin internet, tu biblioteca sigue disponible con activación offline segura.',");
        sb.AppendLine("    trust_three_title: 'Privacidad incluida',");
        sb.AppendLine("    trust_three_desc: 'Tu contenido sigue siendo tuyo. Sin nube obligatoria ni explotación de datos.',");
        sb.AppendLine("    link_terms: 'Términos',");
        sb.AppendLine("    link_privacy: 'Privacidad',");
        sb.AppendLine("    link_imprint: 'Aviso legal',");
        sb.AppendLine("    link_withdrawal: 'Desistimiento',");
        sb.AppendLine("    footer_brand: 'Medios que se sienten como el futuro.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — el nuevo estándar para una gestión multimedia exigente.'");
        sb.AppendLine("  },");
        sb.AppendLine("  it: {");
        sb.AppendLine("    nav_pricing: 'Prezzi e licenza',");
        sb.AppendLine("    pill: 'Controllo media premium',");
        sb.AppendLine("    hero_title: 'Il centro media professionale per chi non accetta compromessi.',");
        sb.AppendLine("    hero_subtitle: 'Cerca, indicizza e vivi video, foto e documenti in pochi secondi con un’interfaccia che sembra magia.',");
        sb.AppendLine("    cta_primary: 'Sblocca Pro',");
        sb.AppendLine("    cta_secondary: 'Scopri le funzioni',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'ricerca più veloce',");
        sb.AppendLine("    stat_two_value: '1 click',");
        sb.AppendLine("    stat_two_label: 'alla vista perfetta',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'focus sui tuoi dati',");
        sb.AppendLine("    hero_image_caption: 'Visualizzazione dell’app con asset originali',");
        sb.AppendLine("    features_title: 'Un’esperienza che eleva ogni contenuto',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro unisce velocità, intelligenza e design per non farti mai aspettare.',");
        sb.AppendLine("    feature_one_title: 'Gestore fonti intelligente',");
        sb.AppendLine("    feature_one_desc: 'Collega cartelle, dischi e backup: tutto organizzato automaticamente e sempre pronto.',");
        sb.AppendLine("    feature_two_title: 'Anteprima immediata',");
        sb.AppendLine("    feature_two_desc: 'Guarda subito i momenti chiave, senza attese o interruzioni.',");
        sb.AppendLine("    feature_three_title: 'Riconoscimento intelligente',");
        sb.AppendLine("    feature_three_desc: 'Trova contenuti per volti, luoghi o tag. La libreria risponde prima che tu chieda.',");
        sb.AppendLine("    feature_four_title: 'Indicizzazione turbo',");
        sb.AppendLine("    feature_four_desc: 'Un nuovo livello di performance rende ricercabili all’istante anche le librerie immense.',");
        sb.AppendLine("    gallery_title: 'Design che ispira fiducia',");
        sb.AppendLine("    gallery_sub: 'Grafiche professionali e asset reali dell’app danno un’impressione premium.',");
        sb.AppendLine("    gallery_caption_one: 'Look cinematografico per la tua libreria — ispirato a visuali libere Unsplash.',");
        sb.AppendLine("    gallery_caption_two: 'Estetica tecnologica che comunica professionalità.',");
        sb.AppendLine("    pricing_title: 'Paga una volta. Godi per sempre.',");
        sb.AppendLine("    pricing_sub: 'Niente abbonamenti o costi nascosti. Sblocca una volta e tieni tutte le funzioni Pro.',");
        sb.AppendLine("    pricing_value: '39 €',");
        sb.AppendLine("    pricing_note: 'include gli aggiornamenti della versione principale attuale',");
        sb.AppendLine("    pricing_cta: 'Assicura Pro',");
        sb.AppendLine("    trust_title: 'Pensato per i professionisti, amato dagli appassionati',");
        sb.AppendLine("    trust_sub: 'Dai filmmaker agli studi: UltimateVideoBrowser Pro offre ordine, velocità e wow effect.',");
        sb.AppendLine("    trust_one_title: 'Multipiattaforma',");
        sb.AppendLine("    trust_one_desc: 'Usa la licenza su Windows e Android con la stessa esperienza premium.',");
        sb.AppendLine("    trust_two_title: 'Pronto offline',");
        sb.AppendLine("    trust_two_desc: 'Anche senza internet, la libreria resta disponibile grazie all’attivazione offline sicura.',");
        sb.AppendLine("    trust_three_title: 'Privacy inclusa',");
        sb.AppendLine("    trust_three_desc: 'I tuoi contenuti restano tuoi. Nessun cloud obbligatorio, nessun utilizzo dei dati.',");
        sb.AppendLine("    link_terms: 'Termini',");
        sb.AppendLine("    link_privacy: 'Privacy',");
        sb.AppendLine("    link_imprint: 'Impressum',");
        sb.AppendLine("    link_withdrawal: 'Recesso',");
        sb.AppendLine("    footer_brand: 'Media che sembrano il futuro.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — il nuovo standard per una gestione media esigente.'");
        sb.AppendLine("  },");
        sb.AppendLine("  pt: {");
        sb.AppendLine("    nav_pricing: 'Preço e licença',");
        sb.AppendLine("    pill: 'Controle de mídia premium',");
        sb.AppendLine("    hero_title: 'O centro profissional de mídia para quem não aceita compromissos.',");
        sb.AppendLine("    hero_subtitle: 'Pesquise, indexe e vivencie seus vídeos, fotos e documentos em segundos com uma interface que parece mágica.',");
        sb.AppendLine("    cta_primary: 'Desbloquear Pro',");
        sb.AppendLine("    cta_secondary: 'Explorar recursos',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'busca mais rápida',");
        sb.AppendLine("    stat_two_value: '1 clique',");
        sb.AppendLine("    stat_two_label: 'para a visão perfeita',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'foco nos seus dados',");
        sb.AppendLine("    hero_image_caption: 'Visualização do app com ativos originais',");
        sb.AppendLine("    features_title: 'Uma experiência que eleva cada mídia',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro combina velocidade, inteligência e design para você nunca esperar.',");
        sb.AppendLine("    feature_one_title: 'Gerenciador de fontes inteligente',");
        sb.AppendLine("    feature_one_desc: 'Conecte pastas, discos e backups — organização automática e sempre pronta.',");
        sb.AppendLine("    feature_two_title: 'Prévia instantânea',");
        sb.AppendLine("    feature_two_desc: 'Veja momentos-chave imediatamente, sem espera ou interrupções.',");
        sb.AppendLine("    feature_three_title: 'Reconhecimento inteligente',");
        sb.AppendLine("    feature_three_desc: 'Encontre conteúdo por rostos, lugares ou tags. Sua biblioteca responde antes do pedido.',");
        sb.AppendLine("    feature_four_title: 'Indexação turbo',");
        sb.AppendLine("    feature_four_desc: 'Um novo nível de desempenho torna até bibliotecas enormes pesquisáveis instantaneamente.',");
        sb.AppendLine("    gallery_title: 'Design que inspira confiança',");
        sb.AppendLine("    gallery_sub: 'Gráficos profissionais e assets reais do app entregam uma impressão premium.',");
        sb.AppendLine("    gallery_caption_one: 'Visual cinematográfico para sua biblioteca — inspirado por imagens livres do Unsplash.',");
        sb.AppendLine("    gallery_caption_two: 'Estética tecnológica que transmite profissionalismo.',");
        sb.AppendLine("    pricing_title: 'Pague uma vez. Aproveite para sempre.',");
        sb.AppendLine("    pricing_sub: 'Sem assinaturas ou taxas ocultas. Desbloqueie uma vez e mantenha todos os recursos Pro.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'inclui atualizações da versão principal atual',");
        sb.AppendLine("    pricing_cta: 'Garantir Pro',");
        sb.AppendLine("    trust_title: 'Feito para profissionais, amado por entusiastas',");
        sb.AppendLine("    trust_sub: 'De criadores a equipes de estúdio: UltimateVideoBrowser Pro oferece ordem, velocidade e efeito wow.',");
        sb.AppendLine("    trust_one_title: 'Multiplataforma',");
        sb.AppendLine("    trust_one_desc: 'Use sua licença no Windows e Android com a mesma experiência premium.',");
        sb.AppendLine("    trust_two_title: 'Pronto para offline',");
        sb.AppendLine("    trust_two_desc: 'Mesmo sem internet, sua biblioteca permanece disponível com ativação offline segura.',");
        sb.AppendLine("    trust_three_title: 'Privacidade incluída',");
        sb.AppendLine("    trust_three_desc: 'Seu conteúdo continua sendo seu. Sem nuvem obrigatória ou exploração de dados.',");
        sb.AppendLine("    link_terms: 'Termos',");
        sb.AppendLine("    link_privacy: 'Privacidade',");
        sb.AppendLine("    link_imprint: 'Impressum',");
        sb.AppendLine("    link_withdrawal: 'Cancelamento',");
        sb.AppendLine("    footer_brand: 'Mídia que parece o futuro.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — o novo padrão para gestão de mídia exigente.'");
        sb.AppendLine("  },");
        sb.AppendLine("  nl: {");
        sb.AppendLine("    nav_pricing: 'Prijs & licentie',");
        sb.AppendLine("    pill: 'Premium mediacontrole',");
        sb.AppendLine("    hero_title: 'Het professionele mediacentrum voor wie geen compromis accepteert.',");
        sb.AppendLine("    hero_subtitle: 'Zoek, indexeer en beleef je video’s, foto’s en documenten in seconden met een magische interface.',");
        sb.AppendLine("    cta_primary: 'Pro ontgrendelen',");
        sb.AppendLine("    cta_secondary: 'Ontdek functies',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'sneller vinden',");
        sb.AppendLine("    stat_two_value: '1 klik',");
        sb.AppendLine("    stat_two_label: 'naar de perfecte weergave',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'focus op jouw data',");
        sb.AppendLine("    hero_image_caption: 'App-visualisatie met originele assets',");
        sb.AppendLine("    features_title: 'Een ervaring die je media naar een hoger niveau tilt',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro combineert snelheid, intelligentie en design zodat je nooit hoeft te wachten.',");
        sb.AppendLine("    feature_one_title: 'Slimme bronnenbeheerder',");
        sb.AppendLine("    feature_one_desc: 'Koppel mappen, schijven en back-ups – automatisch georganiseerd en altijd klaar.',");
        sb.AppendLine("    feature_two_title: 'Directe preview',");
        sb.AppendLine("    feature_two_desc: 'Zie belangrijke momenten meteen, zonder wachttijd of onderbreking.',");
        sb.AppendLine("    feature_three_title: 'Intelligente herkenning',");
        sb.AppendLine("    feature_three_desc: 'Vind content via gezichten, locaties of tags. Je bibliotheek reageert vooruit.',");
        sb.AppendLine("    feature_four_title: 'Turbo-indexering',");
        sb.AppendLine("    feature_four_desc: 'Een nieuw prestatieniveau maakt zelfs enorme bibliotheken direct doorzoekbaar.',");
        sb.AppendLine("    gallery_title: 'Design dat vertrouwen wekt',");
        sb.AppendLine("    gallery_sub: 'Professionele graphics en echte app-assets zorgen voor een premium indruk.',");
        sb.AppendLine("    gallery_caption_one: 'Cinematische stijl voor je bibliotheek — geïnspireerd door vrije Unsplash-beelden.',");
        sb.AppendLine("    gallery_caption_two: 'Technologische esthetiek die professionaliteit uitstraalt.',");
        sb.AppendLine("    pricing_title: 'Betaal één keer. Geniet voor altijd.',");
        sb.AppendLine("    pricing_sub: 'Geen abonnementen of verborgen kosten. Eén keer ontgrendelen en alle Pro-functies behouden.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'inclusief updates voor de huidige hoofdversie',");
        sb.AppendLine("    pricing_cta: 'Pro veiligstellen',");
        sb.AppendLine("    trust_title: 'Gebouwd voor professionals, geliefd bij enthousiastelingen',");
        sb.AppendLine("    trust_sub: 'Van hobbyfilmer tot studioteam: UltimateVideoBrowser Pro levert orde, snelheid en wow-momenten.',");
        sb.AppendLine("    trust_one_title: 'Cross-platform',");
        sb.AppendLine("    trust_one_desc: 'Gebruik je licentie op Windows en Android met dezelfde premium ervaring.',");
        sb.AppendLine("    trust_two_title: 'Offline klaar',");
        sb.AppendLine("    trust_two_desc: 'Zelfs zonder internet blijft je bibliotheek beschikbaar dankzij veilige offline activatie.',");
        sb.AppendLine("    trust_three_title: 'Privacy inbegrepen',");
        sb.AppendLine("    trust_three_desc: 'Je content blijft van jou. Geen verplichte cloud, geen dataverkoop.',");
        sb.AppendLine("    link_terms: 'Voorwaarden',");
        sb.AppendLine("    link_privacy: 'Privacy',");
        sb.AppendLine("    link_imprint: 'Imprint',");
        sb.AppendLine("    link_withdrawal: 'Herroeping',");
        sb.AppendLine("    footer_brand: 'Media die als toekomst voelt.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — de nieuwe standaard voor veeleisend mediabeheer.'");
        sb.AppendLine("  },");
        sb.AppendLine("  pl: {");
        sb.AppendLine("    nav_pricing: 'Cena i licencja',");
        sb.AppendLine("    pill: 'Premium kontrola multimediów',");
        sb.AppendLine("    hero_title: 'Profesjonalne centrum multimediów dla tych, którzy nie uznają kompromisów.',");
        sb.AppendLine("    hero_subtitle: 'Szukaj, indeksuj i oglądaj filmy, zdjęcia i dokumenty w kilka sekund dzięki interfejsowi jak magia.',");
        sb.AppendLine("    cta_primary: 'Odblokuj Pro',");
        sb.AppendLine("    cta_secondary: 'Poznaj funkcje',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'szybsze wyszukiwanie',");
        sb.AppendLine("    stat_two_value: '1 klik',");
        sb.AppendLine("    stat_two_label: 'do idealnego widoku',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'skupienie na danych',");
        sb.AppendLine("    hero_image_caption: 'Wizualizacja aplikacji z oryginalnymi zasobami',");
        sb.AppendLine("    features_title: 'Doświadczenie, które wynosi Twoje multimedia na wyższy poziom',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro łączy szybkość, inteligencję i design, abyś nigdy nie czekał.',");
        sb.AppendLine("    feature_one_title: 'Inteligentny menedżer źródeł',");
        sb.AppendLine("    feature_one_desc: 'Podłącz foldery, dyski i kopie zapasowe — automatycznie uporządkowane i zawsze gotowe.',");
        sb.AppendLine("    feature_two_title: 'Natychmiastowy podgląd',");
        sb.AppendLine("    feature_two_desc: 'Zobacz kluczowe momenty od razu — bez czekania i przerw.',");
        sb.AppendLine("    feature_three_title: 'Inteligentne rozpoznawanie',");
        sb.AppendLine("    feature_three_desc: 'Znajduj treści po twarzach, miejscach lub tagach. Biblioteka reaguje zanim zapytasz.',");
        sb.AppendLine("    feature_four_title: 'Turboindeksowanie',");
        sb.AppendLine("    feature_four_desc: 'Nowy poziom wydajności sprawia, że nawet ogromne biblioteki są przeszukiwalne natychmiast.',");
        sb.AppendLine("    gallery_title: 'Design, który budzi zaufanie',");
        sb.AppendLine("    gallery_sub: 'Profesjonalne grafiki i prawdziwe zasoby aplikacji tworzą premium wrażenie.',");
        sb.AppendLine("    gallery_caption_one: 'Filmowy styl biblioteki — inspirowany darmowymi grafikami Unsplash.',");
        sb.AppendLine("    gallery_caption_two: 'Estetyka technologii, która emanuje profesjonalizmem.',");
        sb.AppendLine("    pricing_title: 'Zapłać raz. Korzystaj na zawsze.',");
        sb.AppendLine("    pricing_sub: 'Brak subskrypcji i ukrytych opłat. Odblokuj raz i zachowaj wszystkie funkcje Pro.',");
        sb.AppendLine("    pricing_value: '39 €',");
        sb.AppendLine("    pricing_note: 'obejmuje aktualizacje bieżącej głównej wersji',");
        sb.AppendLine("    pricing_cta: 'Zabezpiecz Pro',");
        sb.AppendLine("    trust_title: 'Stworzone dla profesjonalistów, uwielbiane przez entuzjastów',");
        sb.AppendLine("    trust_sub: 'Od hobbystów po studia: UltimateVideoBrowser Pro daje porządek, szybkość i efekt wow.',");
        sb.AppendLine("    trust_one_title: 'Wieloplatformowość',");
        sb.AppendLine("    trust_one_desc: 'Używaj licencji na Windows i Android z tym samym premium doświadczeniem.',");
        sb.AppendLine("    trust_two_title: 'Gotowe offline',");
        sb.AppendLine("    trust_two_desc: 'Nawet bez internetu biblioteka pozostaje dostępna dzięki bezpiecznej aktywacji offline.',");
        sb.AppendLine("    trust_three_title: 'Prywatność w standardzie',");
        sb.AppendLine("    trust_three_desc: 'Twoje treści pozostają Twoje. Bez obowiązkowej chmury i bez sprzedaży danych.',");
        sb.AppendLine("    link_terms: 'Warunki',");
        sb.AppendLine("    link_privacy: 'Prywatność',");
        sb.AppendLine("    link_imprint: 'Imprint',");
        sb.AppendLine("    link_withdrawal: 'Odstąpienie',");
        sb.AppendLine("    footer_brand: 'Media, które smakują przyszłością.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — nowy standard dla wymagającego zarządzania mediami.'");
        sb.AppendLine("  },");
        sb.AppendLine("  tr: {");
        sb.AppendLine("    nav_pricing: 'Fiyat ve lisans',");
        sb.AppendLine("    pill: 'Premium medya kontrolü',");
        sb.AppendLine("    hero_title: 'Taviz kabul etmeyenler için profesyonel medya komuta merkezi.',");
        sb.AppendLine("    hero_subtitle: 'Videolarını, fotoğraflarını ve belgelerini saniyeler içinde ara, indeksle ve büyü gibi bir arayüzle deneyimle.',");
        sb.AppendLine("    cta_primary: 'Pro’yu aç',");
        sb.AppendLine("    cta_secondary: 'Özellikleri keşfet',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'daha hızlı bulma',");
        sb.AppendLine("    stat_two_value: '1 tık',");
        sb.AppendLine("    stat_two_label: 'mükemmel görünüme',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'verilerine odaklı',");
        sb.AppendLine("    hero_image_caption: 'Orijinal varlıklarla uygulama görseli',");
        sb.AppendLine("    features_title: 'Her medyayı üst seviyeye taşıyan bir deneyim',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro hız, zeka ve tasarımı birleştirir; bekletmez.',");
        sb.AppendLine("    feature_one_title: 'Akıllı kaynak yöneticisi',");
        sb.AppendLine("    feature_one_desc: 'Klasörleri, diskleri ve yedekleri bağla — otomatik düzen, her zaman hazır.',");
        sb.AppendLine("    feature_two_title: 'Anında ön izleme',");
        sb.AppendLine("    feature_two_desc: 'Önemli anları hemen gör — bekleme yok, kesinti yok.',");
        sb.AppendLine("    feature_three_title: 'Akıllı tanıma',");
        sb.AppendLine("    feature_three_desc: 'Yüz, yer veya etiketlerle içerik bul. Kütüphanen senden önce cevap verir.',");
        sb.AppendLine("    feature_four_title: 'Turbo indeksleme',");
        sb.AppendLine("    feature_four_desc: 'Yeni performans seviyesi, dev kütüphaneleri bile anında aranabilir yapar.',");
        sb.AppendLine("    gallery_title: 'Güven veren tasarım',");
        sb.AppendLine("    gallery_sub: 'Profesyonel grafikler ve gerçek uygulama varlıkları premium hissi verir.',");
        sb.AppendLine("    gallery_caption_one: 'Kütüphanen için sinematik görünüm — ücretsiz Unsplash görsellerinden ilham.',");
        sb.AppendLine("    gallery_caption_two: 'Profesyonellik yayan teknoloji estetiği.',");
        sb.AppendLine("    pricing_title: 'Bir kez öde. Sonsuza kadar kullan.',");
        sb.AppendLine("    pricing_sub: 'Abonelik yok, gizli ücret yok. Bir kez aç ve tüm Pro özelliklerini koru.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'geçerli ana sürüm güncellemeleri dahil',");
        sb.AppendLine("    pricing_cta: 'Pro’yu al',");
        sb.AppendLine("    trust_title: 'Profesyoneller için tasarlandı, meraklılar tarafından sevildi',");
        sb.AppendLine("    trust_sub: 'Hobi filmcilerden stüdyo ekiplerine: UltimateVideoBrowser Pro düzen, hız ve wow sunar.',");
        sb.AppendLine("    trust_one_title: 'Çapraz platform',");
        sb.AppendLine("    trust_one_desc: 'Lisansını Windows ve Android’de aynı premium deneyimle kullan.',");
        sb.AppendLine("    trust_two_title: 'Offline hazır',");
        sb.AppendLine("    trust_two_desc: 'İnternet olmasa bile kütüphanen güvenli offline aktivasyonla erişilebilir.',");
        sb.AppendLine("    trust_three_title: 'Gizlilik dahil',");
        sb.AppendLine("    trust_three_desc: 'İçeriğin sana ait. Zorunlu bulut yok, veri satışı yok.',");
        sb.AppendLine("    link_terms: 'Şartlar',");
        sb.AppendLine("    link_privacy: 'Gizlilik',");
        sb.AppendLine("    link_imprint: 'İmprint',");
        sb.AppendLine("    link_withdrawal: 'Cayma',");
        sb.AppendLine("    footer_brand: 'Gelecek gibi hissettiren medya.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — seçici medya yönetimi için yeni standart.'");
        sb.AppendLine("  },");
        sb.AppendLine("  ru: {");
        sb.AppendLine("    nav_pricing: 'Цена и лицензия',");
        sb.AppendLine("    pill: 'Премиум-контроль медиа',");
        sb.AppendLine("    hero_title: 'Профессиональный центр управления медиа для тех, кто не принимает компромиссы.',");
        sb.AppendLine("    hero_subtitle: 'Ищите, индексируйте и наслаждайтесь видео, фото и документами за секунды с интерфейсом как магия.',");
        sb.AppendLine("    cta_primary: 'Открыть Pro',");
        sb.AppendLine("    cta_secondary: 'Посмотреть функции',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'быстрее поиск',");
        sb.AppendLine("    stat_two_value: '1 клик',");
        sb.AppendLine("    stat_two_label: 'до идеального вида',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'фокус на ваших данных',");
        sb.AppendLine("    hero_image_caption: 'Визуализация приложения с оригинальными ассетами',");
        sb.AppendLine("    features_title: 'Опыт, поднимающий ваши медиа на новый уровень',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro объединяет скорость, интеллект и дизайн, чтобы вы не ждали.',");
        sb.AppendLine("    feature_one_title: 'Умный менеджер источников',");
        sb.AppendLine("    feature_one_desc: 'Подключайте папки, диски и резервные копии — всё организовано автоматически.',");
        sb.AppendLine("    feature_two_title: 'Мгновенный предпросмотр',");
        sb.AppendLine("    feature_two_desc: 'Смотрите ключевые моменты сразу — без ожиданий и пауз.',");
        sb.AppendLine("    feature_three_title: 'Интеллектуальное распознавание',");
        sb.AppendLine("    feature_three_desc: 'Ищите по лицам, местам или тегам. Библиотека отвечает раньше, чем вы спросите.',");
        sb.AppendLine("    feature_four_title: 'Турбо-индексация',");
        sb.AppendLine("    feature_four_desc: 'Новый уровень производительности делает огромные библиотеки мгновенно доступными.',");
        sb.AppendLine("    gallery_title: 'Дизайн, которому доверяют',");
        sb.AppendLine("    gallery_sub: 'Профессиональная графика и реальные ассеты приложения создают премиальное впечатление.',");
        sb.AppendLine("    gallery_caption_one: 'Кинематографичный стиль библиотеки — вдохновлено бесплатными визуалами Unsplash.',");
        sb.AppendLine("    gallery_caption_two: 'Технологичная эстетика, излучающая профессионализм.',");
        sb.AppendLine("    pricing_title: 'Платите один раз. Пользуйтесь всегда.',");
        sb.AppendLine("    pricing_sub: 'Никаких подписок и скрытых платежей. Разблокируйте один раз и сохраните все Pro-функции.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'включает обновления текущей основной версии',");
        sb.AppendLine("    pricing_cta: 'Получить Pro',");
        sb.AppendLine("    trust_title: 'Создано для профессионалов, любимо энтузиастами',");
        sb.AppendLine("    trust_sub: 'От любителей до студий: UltimateVideoBrowser Pro дарит порядок, скорость и вау-эффект.',");
        sb.AppendLine("    trust_one_title: 'Кроссплатформенность',");
        sb.AppendLine("    trust_one_desc: 'Используйте лицензию на Windows и Android с одинаковым премиум-опытом.',");
        sb.AppendLine("    trust_two_title: 'Готово офлайн',");
        sb.AppendLine("    trust_two_desc: 'Даже без интернета библиотека доступна благодаря безопасной офлайн-активации.',");
        sb.AppendLine("    trust_three_title: 'Приватность включена',");
        sb.AppendLine("    trust_three_desc: 'Ваш контент остаётся вашим. Никакого обязательного облака и продажи данных.',");
        sb.AppendLine("    link_terms: 'Условия',");
        sb.AppendLine("    link_privacy: 'Конфиденциальность',");
        sb.AppendLine("    link_imprint: 'Imprint',");
        sb.AppendLine("    link_withdrawal: 'Отказ',");
        sb.AppendLine("    footer_brand: 'Медиа, которые ощущаются как будущее.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — новый стандарт требовательного управления медиа.'");
        sb.AppendLine("  },");
        sb.AppendLine("  zh: {");
        sb.AppendLine("    nav_pricing: '价格与许可',");
        sb.AppendLine("    pill: '高端媒体掌控',");
        sb.AppendLine("    hero_title: '为不妥协的人打造的专业媒体指挥中心。',");
        sb.AppendLine("    hero_subtitle: '在数秒内搜索、索引并体验视频、照片和文档，界面如同魔法般顺畅。',");
        sb.AppendLine("    cta_primary: '立即解锁 Pro',");
        sb.AppendLine("    cta_secondary: '探索功能',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: '更快查找',");
        sb.AppendLine("    stat_two_value: '1 次点击',");
        sb.AppendLine("    stat_two_label: '直达完美视图',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: '专注你的数据',");
        sb.AppendLine("    hero_image_caption: '使用原始素材的应用视觉',");
        sb.AppendLine("    features_title: '让每一份媒体都焕然一新的体验',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro 融合速度、智能与设计，让你从不等待。',");
        sb.AppendLine("    feature_one_title: '智能来源管理',");
        sb.AppendLine("    feature_one_desc: '连接文件夹、硬盘与备份——自动整理，随时就绪。',");
        sb.AppendLine("    feature_two_title: '即时预览',");
        sb.AppendLine("    feature_two_desc: '关键时刻即刻可见，无需等待、无需打断。',");
        sb.AppendLine("    feature_three_title: '智能识别',");
        sb.AppendLine("    feature_three_desc: '按人脸、地点或标签查找内容，媒体库比你更先一步。',");
        sb.AppendLine("    feature_four_title: '极速索引',");
        sb.AppendLine("    feature_four_desc: '全新性能级别让超大库也能瞬间搜索。',");
        sb.AppendLine("    gallery_title: '值得信赖的设计',");
        sb.AppendLine("    gallery_sub: '专业图形与真实应用素材营造尊贵体验。',");
        sb.AppendLine("    gallery_caption_one: '为你的媒体库带来电影质感——灵感来自免费 Unsplash 视觉。',");
        sb.AppendLine("    gallery_caption_two: '科技美学散发专业气质。',");
        sb.AppendLine("    pricing_title: '一次购买，永久享受。',");
        sb.AppendLine("    pricing_sub: '无订阅、无隐藏费用。一次解锁，Pro 功能永久拥有。',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: '包含当前主版本更新',");
        sb.AppendLine("    pricing_cta: '立即获取 Pro',");
        sb.AppendLine("    trust_title: '为专业人士打造，深受爱好者喜爱',");
        sb.AppendLine("    trust_sub: '从爱好者到工作室团队：UltimateVideoBrowser Pro 带来秩序、速度与惊艳体验。',");
        sb.AppendLine("    trust_one_title: '跨平台',");
        sb.AppendLine("    trust_one_desc: '在 Windows 与 Android 上使用同一许可证，体验一致的高级品质。',");
        sb.AppendLine("    trust_two_title: '离线可用',");
        sb.AppendLine("    trust_two_desc: '即使没有网络，安全离线激活也能保持可用。',");
        sb.AppendLine("    trust_three_title: '隐私保障',");
        sb.AppendLine("    trust_three_desc: '你的内容只属于你。无需云端、不会挖掘数据。',");
        sb.AppendLine("    link_terms: '条款',");
        sb.AppendLine("    link_privacy: '隐私',");
        sb.AppendLine("    link_imprint: '版权信息',");
        sb.AppendLine("    link_withdrawal: '撤销',");
        sb.AppendLine("    footer_brand: '让媒体拥有未来感。',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — 高标准媒体管理的新标杆。'");
        sb.AppendLine("  },");
        sb.AppendLine("  ja: {");
        sb.AppendLine("    nav_pricing: '価格とライセンス',");
        sb.AppendLine("    pill: 'プレミアムメディア管理',");
        sb.AppendLine("    hero_title: '妥協を許さない人のためのプロフェッショナルなメディア司令塔。',");
        sb.AppendLine("    hero_subtitle: '動画・写真・ドキュメントを数秒で検索・インデックス化。魔法のようなUIで体験。',");
        sb.AppendLine("    cta_primary: 'Pro を解除',");
        sb.AppendLine("    cta_secondary: '機能を見る',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: '検索が高速',");
        sb.AppendLine("    stat_two_value: '1 クリック',");
        sb.AppendLine("    stat_two_label: '理想のビューへ',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'データに集中',");
        sb.AppendLine("    hero_image_caption: 'オリジナル素材を使ったアプリビジュアル',");
        sb.AppendLine("    features_title: 'メディア体験を次のレベルへ',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro は速度・知性・デザインを融合し、待ち時間をゼロへ。',");
        sb.AppendLine("    feature_one_title: 'スマートなソース管理',");
        sb.AppendLine("    feature_one_desc: 'フォルダ、ドライブ、バックアップを自動整理して接続。',");
        sb.AppendLine("    feature_two_title: '即時プレビュー',");
        sb.AppendLine("    feature_two_desc: '重要な瞬間をすぐに表示。待ち時間なし。',");
        sb.AppendLine("    feature_three_title: 'インテリジェント認識',");
        sb.AppendLine("    feature_three_desc: '顔・場所・タグで検索。ライブラリが先回りします。',");
        sb.AppendLine("    feature_four_title: 'ターボインデックス',");
        sb.AppendLine("    feature_four_desc: '巨大なライブラリでも瞬時に検索可能。',");
        sb.AppendLine("    gallery_title: '信頼を生むデザイン',");
        sb.AppendLine("    gallery_sub: 'プロ品質のグラフィックと実際のアセットがプレミアム感を演出。',");
        sb.AppendLine("    gallery_caption_one: '無料の Unsplash ビジュアルに着想を得たシネマティックスタイル。',");
        sb.AppendLine("    gallery_caption_two: 'プロフェッショナルさを感じさせるテック美学。',");
        sb.AppendLine("    pricing_title: '一度の支払いで永遠に。',");
        sb.AppendLine("    pricing_sub: 'サブスクや隠れた費用なし。一度の解除で Pro 機能をすべて利用。',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: '現在のメジャーバージョンの更新を含む',");
        sb.AppendLine("    pricing_cta: 'Pro を入手',");
        sb.AppendLine("    trust_title: 'プロに選ばれ、愛好家に愛される',");
        sb.AppendLine("    trust_sub: '趣味の映像制作からスタジオチームまで：秩序とスピード、感動体験を提供。',");
        sb.AppendLine("    trust_one_title: 'クロスプラットフォーム',");
        sb.AppendLine("    trust_one_desc: 'Windows と Android で同じプレミアム体験を提供。',");
        sb.AppendLine("    trust_two_title: 'オフライン対応',");
        sb.AppendLine("    trust_two_desc: 'インターネットがなくても、安全なオフライン認証で利用可能。',");
        sb.AppendLine("    trust_three_title: 'プライバシー重視',");
        sb.AppendLine("    trust_three_desc: 'コンテンツはあなたのもの。強制クラウドもデータ収集もなし。',");
        sb.AppendLine("    link_terms: '利用規約',");
        sb.AppendLine("    link_privacy: 'プライバシー',");
        sb.AppendLine("    link_imprint: '法的情報',");
        sb.AppendLine("    link_withdrawal: '解約',");
        sb.AppendLine("    footer_brand: '未来を感じるメディア体験。',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — こだわりのメディア管理の新基準。'");
        sb.AppendLine("  },");
        sb.AppendLine("  ko: {");
        sb.AppendLine("    nav_pricing: '가격 및 라이선스',");
        sb.AppendLine("    pill: '프리미엄 미디어 컨트롤',");
        sb.AppendLine("    hero_title: '타협을 모르는 사람들을 위한 전문 미디어 커맨드 센터.',");
        sb.AppendLine("    hero_subtitle: '영상, 사진, 문서를 몇 초 만에 검색하고 인덱싱하세요. 마법 같은 UI가 함께합니다.',");
        sb.AppendLine("    cta_primary: 'Pro 잠금 해제',");
        sb.AppendLine("    cta_secondary: '기능 보기',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: '더 빠른 검색',");
        sb.AppendLine("    stat_two_value: '1 클릭',");
        sb.AppendLine("    stat_two_label: '완벽한 보기로',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: '데이터에 집중',");
        sb.AppendLine("    hero_image_caption: '오리지널 에셋을 사용한 앱 비주얼',");
        sb.AppendLine("    features_title: '모든 미디어 경험을 한 단계 끌어올리다',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro는 속도, 지능, 디자인을 결합해 기다림을 없앱니다.',");
        sb.AppendLine("    feature_one_title: '스마트 소스 매니저',");
        sb.AppendLine("    feature_one_desc: '폴더, 드라이브, 백업을 연결하면 자동으로 정리됩니다.',");
        sb.AppendLine("    feature_two_title: '즉시 미리보기',");
        sb.AppendLine("    feature_two_desc: '중요한 순간을 즉시 확인—대기 없음.',");
        sb.AppendLine("    feature_three_title: '지능형 인식',");
        sb.AppendLine("    feature_three_desc: '얼굴, 장소, 태그로 찾기. 라이브러리가 먼저 반응합니다.',");
        sb.AppendLine("    feature_four_title: '터보 인덱싱',");
        sb.AppendLine("    feature_four_desc: '거대한 라이브러리도 즉시 검색 가능하게 만드는 성능.',");
        sb.AppendLine("    gallery_title: '신뢰를 만드는 디자인',");
        sb.AppendLine("    gallery_sub: '프로급 그래픽과 실제 앱 에셋이 프리미엄 인상을 선사합니다.',");
        sb.AppendLine("    gallery_caption_one: '무료 Unsplash 비주얼에서 영감을 받은 시네마틱 스타일.',");
        sb.AppendLine("    gallery_caption_two: '전문성을 강조하는 테크 감성.',");
        sb.AppendLine("    pricing_title: '한 번 결제, 영원히 사용.',");
        sb.AppendLine("    pricing_sub: '구독이나 숨겨진 비용 없이 한 번만 잠금 해제하세요.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: '현재 메이저 버전 업데이트 포함',");
        sb.AppendLine("    pricing_cta: 'Pro 확보',");
        sb.AppendLine("    trust_title: '프로를 위해 만들고, 팬들에게 사랑받다',");
        sb.AppendLine("    trust_sub: '취미 사용자부터 스튜디오 팀까지: UltimateVideoBrowser Pro는 질서와 속도, 감탄을 제공합니다.',");
        sb.AppendLine("    trust_one_title: '크로스 플랫폼',");
        sb.AppendLine("    trust_one_desc: 'Windows와 Android에서 동일한 프리미엄 경험을 제공합니다.',");
        sb.AppendLine("    trust_two_title: '오프라인 지원',");
        sb.AppendLine("    trust_two_desc: '인터넷이 없어도 안전한 오프라인 활성화로 사용 가능합니다.',");
        sb.AppendLine("    trust_three_title: '프라이버시 포함',");
        sb.AppendLine("    trust_three_desc: '콘텐츠는 당신의 것. 의무적 클라우드나 데이터 수집 없음.',");
        sb.AppendLine("    link_terms: '이용 약관',");
        sb.AppendLine("    link_privacy: '개인정보',");
        sb.AppendLine("    link_imprint: '법적 고지',");
        sb.AppendLine("    link_withdrawal: '철회',");
        sb.AppendLine("    footer_brand: '미래처럼 느껴지는 미디어.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — 까다로운 미디어 관리의 새로운 기준.'");
        sb.AppendLine("  },");
        sb.AppendLine("  ar: {");
        sb.AppendLine("    nav_pricing: 'السعر والترخيص',");
        sb.AppendLine("    pill: 'تحكم وسائط فائق',");
        sb.AppendLine("    hero_title: 'مركز وسائط احترافي لمن لا يقبل التنازل.',");
        sb.AppendLine("    hero_subtitle: 'ابحث وفهرس واستمتع بمقاطع الفيديو والصور والمستندات خلال ثوانٍ بواجهة تبدو كالسحر.',");
        sb.AppendLine("    cta_primary: 'فعّل Pro الآن',");
        sb.AppendLine("    cta_secondary: 'اكتشف الميزات',");
        sb.AppendLine("    stat_one_value: '3×',");
        sb.AppendLine("    stat_one_label: 'بحث أسرع',");
        sb.AppendLine("    stat_two_value: 'نقرة واحدة',");
        sb.AppendLine("    stat_two_label: 'للوصول إلى العرض المثالي',");
        sb.AppendLine("    stat_three_value: '100%',");
        sb.AppendLine("    stat_three_label: 'تركيز على بياناتك',");
        sb.AppendLine("    hero_image_caption: 'تصور للتطبيق باستخدام الأصول الأصلية',");
        sb.AppendLine("    features_title: 'تجربة ترتقي بكل وسائطك',");
        sb.AppendLine("    features_sub: 'UltimateVideoBrowser Pro يجمع السرعة والذكاء والتصميم لتبقى دائمًا في المقدمة.',");
        sb.AppendLine("    feature_one_title: 'مدير مصادر ذكي',");
        sb.AppendLine("    feature_one_desc: 'اربط المجلدات والأقراص والنسخ الاحتياطية — تنظيم تلقائي وجاهز دائمًا.',");
        sb.AppendLine("    feature_two_title: 'معاينة فورية',");
        sb.AppendLine("    feature_two_desc: 'شاهد اللحظات المهمة فورًا دون انتظار أو انقطاع.',");
        sb.AppendLine("    feature_three_title: 'تعرف ذكي',");
        sb.AppendLine("    feature_three_desc: 'اعثر على المحتوى عبر الوجوه أو الأماكن أو الوسوم. مكتبتك تستبق طلبك.',");
        sb.AppendLine("    feature_four_title: 'فهرسة فائقة السرعة',");
        sb.AppendLine("    feature_four_desc: 'مستوى أداء جديد يجعل حتى المكتبات الضخمة قابلة للبحث فورًا.',");
        sb.AppendLine("    gallery_title: 'تصميم يبني الثقة',");
        sb.AppendLine("    gallery_sub: 'رسومات احترافية وأصول تطبيق حقيقية تمنح إحساسًا فاخرًا.',");
        sb.AppendLine("    gallery_caption_one: 'طابع سينمائي لمكتبتك — مستوحى من صور Unsplash المجانية.',");
        sb.AppendLine("    gallery_caption_two: 'جمالية تقنية تعكس الاحترافية.',");
        sb.AppendLine("    pricing_title: 'ادفع مرة واحدة. واستمتع للأبد.',");
        sb.AppendLine("    pricing_sub: 'لا اشتراكات ولا رسوم خفية. فعّل مرة واحدة واحتفظ بكل ميزات Pro.',");
        sb.AppendLine("    pricing_value: '€39',");
        sb.AppendLine("    pricing_note: 'يشمل تحديثات الإصدار الرئيسي الحالي',");
        sb.AppendLine("    pricing_cta: 'احصل على Pro',");
        sb.AppendLine("    trust_title: 'مصمم للمحترفين ومحبوب من الهواة',");
        sb.AppendLine("    trust_sub: 'من صناع الفيديو الهواة إلى فرق الاستوديو: UltimateVideoBrowser Pro يمنحك النظام والسرعة والإبهار.',");
        sb.AppendLine("    trust_one_title: 'متعدد المنصات',");
        sb.AppendLine("    trust_one_desc: 'استخدم الترخيص على Windows وAndroid بنفس التجربة المميزة.',");
        sb.AppendLine("    trust_two_title: 'جاهز دون اتصال',");
        sb.AppendLine("    trust_two_desc: 'حتى بدون إنترنت تبقى مكتبتك متاحة بفضل التفعيل الآمن دون اتصال.',");
        sb.AppendLine("    trust_three_title: 'خصوصية مضمونة',");
        sb.AppendLine("    trust_three_desc: 'محتواك يبقى ملكك. لا سحابة إلزامية ولا استغلال للبيانات.',");
        sb.AppendLine("    link_terms: 'الشروط',");
        sb.AppendLine("    link_privacy: 'الخصوصية',");
        sb.AppendLine("    link_imprint: 'بيان قانوني',");
        sb.AppendLine("    link_withdrawal: 'إلغاء',");
        sb.AppendLine("    footer_brand: 'وسائط تشعر وكأنها المستقبل.',");
        sb.AppendLine("    footer_note: 'UltimateVideoBrowser Pro — المعيار الجديد لإدارة الوسائط المتقدمة.'");
        sb.AppendLine("  }");
        sb.AppendLine("};");
        sb.AppendLine("const languageNames = {");
        sb.AppendLine("  de: 'Deutsch',");
        sb.AppendLine("  en: 'English',");
        sb.AppendLine("  fr: 'Français',");
        sb.AppendLine("  es: 'Español',");
        sb.AppendLine("  it: 'Italiano',");
        sb.AppendLine("  pt: 'Português',");
        sb.AppendLine("  nl: 'Nederlands',");
        sb.AppendLine("  pl: 'Polski',");
        sb.AppendLine("  tr: 'Türkçe',");
        sb.AppendLine("  ru: 'Русский',");
        sb.AppendLine("  zh: '中文',");
        sb.AppendLine("  ja: '日本語',");
        sb.AppendLine("  ko: '한국어',");
        sb.AppendLine("  ar: 'العربية'");
        sb.AppendLine("};");
        sb.AppendLine("const langSelect = document.getElementById('langSelect');");
        sb.AppendLine("Object.keys(languageNames).forEach(lang => {");
        sb.AppendLine("  const option = document.createElement('option');");
        sb.AppendLine("  option.value = lang; option.textContent = languageNames[lang];");
        sb.AppendLine("  langSelect.appendChild(option);");
        sb.AppendLine("});");
        sb.AppendLine("function resolveLang(preferred){");
        sb.AppendLine("  const normalized = preferred.toLowerCase();");
        sb.AppendLine("  if (translations[normalized]) return normalized;");
        sb.AppendLine("  const prefix = normalized.split('-')[0];");
        sb.AppendLine("  return translations[prefix] ? prefix : 'en';");
        sb.AppendLine("}");
        sb.AppendLine("function applyLang(lang){");
        sb.AppendLine("  const dict = translations[lang] || translations.en;");
        sb.AppendLine("  document.documentElement.lang = lang;" );
        sb.AppendLine("  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';");
        sb.AppendLine("  document.querySelectorAll('[data-i18n]').forEach(el => {");
        sb.AppendLine("    const key = el.getAttribute('data-i18n');");
        sb.AppendLine("    if (dict[key]) el.textContent = dict[key];");
        sb.AppendLine("  });");
        sb.AppendLine("}");
        sb.AppendLine("const preferred = (navigator.languages && navigator.languages.length ? navigator.languages[0] : navigator.language) || 'en';");
        sb.AppendLine("const startLang = resolveLang(preferred);");
        sb.AppendLine("langSelect.value = startLang;");
        sb.AppendLine("applyLang(startLang);");
        sb.AppendLine("langSelect.addEventListener('change', e => applyLang(e.target.value));");
        sb.AppendLine("</script>");
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }
}
